name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'


jobs:
  deploy: 
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/veterinary-clinic:latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Authenticate Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker buildx build --platform linux/amd64 -t ${{ env.IMAGE_NAME }} .

      - name: Configure Docker Client for Artifact Registry
        run: | 
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image.."
          docker push ${{ env.IMAGE_NAME }}
  
      - name: Deploy to GCP Cloud Run
        run: |
          gcloud run deploy veterinary-clinic \
          --image ${{ env.IMAGE_NAME }} \
          --region ${{ secrets.GCP_REGION }} \
          --add-cloudsql-instances ${{ secrets.GCP_DB_INSTANCE }} \
          --platform managed \
          --timeout=300s \
          --allow-unauthenticated
